# Generated by Django 4.2.1 on 2023-10-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='friends',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='friends',
            index=models.Index(fields=['-time_create'], name='myapp_frien_time_cr_6bd116_idx'),
        ),
    ]
