# Generated by Django 4.2.1 on 2023-10-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_friends_options_friends_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
