# Generated by Django 4.2.1 on 2023-11-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_friends_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='friends',
            name='myapp_frien_time_cr_6bd116_idx',
        ),
        migrations.AlterField(
            model_name='friends',
            name='is_the_best',
            field=models.BooleanField(choices=[(0, 'Не лучший друг'), (1, 'Лучший друг')], default=0),
        ),
    ]
