# Generated by Django 4.2.1 on 2023-11-14 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_friends_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='friends',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='myapp.gender'),
        ),
        migrations.AddField(
            model_name='friends',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='myapp.tagfriends'),
        ),
    ]
