# Generated by Django 4.2.1 on 2023-11-16 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_tagfriends_alter_friends_gender_friends_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='GirlFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='friends',
            name='girlfriend',
            field=models.OneToOneField(blank='True', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boyfriend', to='myapp.girlfriend'),
        ),
    ]
