# Generated by Django 4.2.1 on 2023-11-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_girlfriend_friends_girlfriend'),
    ]

    operations = [
        migrations.AddField(
            model_name='girlfriend',
            name='boyfriends_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
